# Generated by Django 3.2.12 on 2022-03-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0004_auto_20220323_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='place_restante',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
