# Generated by Django 3.2.12 on 2022-03-23 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppGestion', '0002_auto_20220323_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asso9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assis', models.BooleanField(verbose_name=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppGestion.evenement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='ticket_achete',
            field=models.ManyToManyField(blank=True, through='AppGestion.Asso9', to=settings.AUTH_USER_MODEL),
        ),
    ]
