# Generated by Django 3.2.12 on 2022-03-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0003_auto_20220323_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppGestion.salle'),
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='intervenant',
        ),
        migrations.AddField(
            model_name='evenement',
            name='intervenant',
            field=models.ManyToManyField(blank=True, to='AppGestion.Intervenant'),
        ),
    ]
