# Generated by Django 4.0.3 on 2022-03-25 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0005_alter_evenement_place_restante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='salle',
        ),
        migrations.AddField(
            model_name='evenement',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppGestion.reservationsalle'),
        ),
    ]
