# Generated by Django 3.2.12 on 2022-03-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0006_remove_evenement_salle_evenement_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asso9',
            name='assis',
        ),
        migrations.AddField(
            model_name='asso9',
            name='nb_place_assise',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asso9',
            name='nb_place_debout',
            field=models.IntegerField(default=0),
        ),
    ]
